name: Pull and Save Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest,ubuntu:latest'  # 设置默认的 Docker 镜像列表
      docker_platform:
        description: '请填写运行平台'
        required: true
        default: 'linux/amd64'  # 设置默认的平台

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull Docker Images and Package
      run: |
        images="${{ github.event.inputs.docker_images }}"
        platform="${{ github.event.inputs.docker_platform }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          docker pull "${image}" --platform "${platform}"
          docker save "${image}" -o "${image//\//_}-images.tar"
        done

    - name: Compress the TAR files
      run: tar -czf docker-images.tar.gz *-images.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar
        path: docker-images.tar.gz
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Clean up intermediate files
      run: |
        rm *-images.tar
